### PR TITLE
Walkthrough

### LINKED ISSUE #91: Goals for making the name server app
1. To understand how different modules and dependencies interact with one another. The Simple storage app only has one user defined module, so is insufficient to check this. 
2. To develop the lower level modules and interfaces for dealing with things like message routing, signature verification (authentication), basic validation of messages, hooks for custom validation.
3. To further abstract common use patterns from simple-storage and name-server and incorporate them into a library.
4. To benchmark a non-trivial application, both as an independent node but potentially as a network.

### LINKED ISSUE #142: Create walkthrough for Nameservice app
Would like to see something like https://github.com/slamdata/purescript-halogen/tree/master/docs

### PR DESCRIPTION
**Pull request by martyall**
fixes #142 
fixes #91

### CODE REVIEW

**Comment by iostat** [comment]
* Does the main README need to be an .lhs? All you have is “First some imports”, the table of contents, and an empty main. Maybe the “Introduction” can be moved right into it?
* For the nameservice section itself, maybe it’d be worthwhile to have a “how this all ties in” as the root of that chapter. (Explain why the files are structured as such as they are)
* Ditto for foundation — maybe a brief overview of /how/ BaseApp and all the modules get tied into IO (other than “it just does” as you have later)

**Review by iostat — APPROVED** [review]
besides aforementioned lgtm

**Comment by kejace** [comment]
Please see https://github.com/f-o-a-m/hs-abci/pull/159 for my edits. Otherwise, amazing job!

**Review by kejace — DISMISSED** [review]
See https://github.com/f-o-a-m/hs-abci/pull/159

**Comment by kejace** [comment]
@blinky3713 My PR #159 is now green.

**Pull request merged**
